name: Code style

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Upgrade pip and install linters
        run: pip install black
      - name: Run black
        run: black . --check

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Upgrade pip and install linters
        run: pip install isort
      - name: Run isort
        run: isort . --check-only

  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -e ".[test]"

      - name: Test with pytest
        run: pytest --cov=lsbi tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
