name: PR checks

on:
  pull_request:
    branches: [master]

jobs:
  version-is-unit-incremented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Upgrade pip and install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install packaging
      - name: Check version number
        run: python ./bin/check_version.py

  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Upgrade pip and install doc requirements
        run: pip install -e ".[all,docs]"
      - name: build documentation
        run: |
          cd docs
          make clean
          make html SPHINXOPTS="-W --keep-going -n"

  test-pypi-release:
    name: Build and deploy to test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install pypa/build
        run: pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
  
  test-conda-release:
    name: Build and deploy to conda
    runs-on: ubuntu-latest
    steps:
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.9'
          auto-activate-base: true
#          environment-file: devtools/conda-envs/build_env.yaml
#          auto-update-conda: false
#          show-channel-urls: true
      - name: install dependencies
        shell: bash -el {0}
        run: conda install grayskull
      - name: Bash
        shell: bash -el {0}
        run: |
          conda info
          conda list
      - name: Generate meta.yaml from grayskull
        shell: bash -el {0}
        run: grayskull pypi --strict-conda-forge lsbi
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: lsbi
          python-version: '3.9'
          platform_linux-64: true
          platform_osx-64: true
          platform_win-64: true
          user: handley-lab
          label: auto
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the right name of your secret

